/* 设计交互层：仅维护页面内的示例状态，不请求模型、数据库或真实文件服务。 */
const paths = {
  new:'M20 11a8 8 0 0 1-8 8H5l-3 2v-7a8 8 0 1 1 18-3ZM12 7v8M8 11h8',
  plus:'M12 5v14M5 12h14', panel:'M6 4h12a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3ZM9 4v16',
  drive:'m4 4-2 9v6a1 1 0 0 0 1 1h18a1 1 0 0 0 1-1v-6l-2-9ZM2 13h20M6 17h.01M10 17h.01',
  books:'M3 4h5v16H3ZM8 4h5v16H8Zm6 1 5-1 3 15-5 1ZM5 8h1M10 8h1',
  book:'M12 5C8 3 5 3 2 5v15c4-2 7-2 10 0 3-2 6-2 10 0V5c-3-2-6-2-10 0ZM12 5v15',
  search:'M17 10.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0Zm-1 5.5 4 4',
  atom:'M12 12h.01M20 12c0 3-3.6 5.5-8 5.5S4 15 4 12 7.6 6.5 12 6.5s8 2.5 8 5.5ZM16 5c2.6 1.5 2.9 5.9.7 9.7s-6.2 5.8-8.8 4.3S5 13.1 7.2 9.3 13.4 3.5 16 5ZM8 5c2.6-1.5 6.6.5 8.8 4.3s1.9 8.2-.7 9.7-6.6-.5-8.8-4.3S5.4 6.5 8 5Z',
  file:'M14 3H5v18h14V8ZM14 3v5h5M8 12h8M8 16h6', folder:'M3 7V4h6l2 3h10v13H3ZM3 7h18',
  status:'M9 5h12M9 12h12M9 19h12M2 4l2 2 2-3M2 11l2 2 2-3M2 18l2 2 2-3',
  chevron:'m8 10 4 4 4-4',right:'m9 5 7 7-7 7',close:'m6 6 12 12M18 6 6 18', more:'M5 12h.01M12 12h.01M19 12h.01',
  arrow:'M12 20V4m-6 6 6-6 6 6', route:'M4 7h14m-4-4 4 4-4 4M20 17H6m4-4-4 4 4 4',
  map:'m2 6 6-3 8 3 6-3v15l-6 3-8-3-6 3ZM8 3v15M16 6v15',
  pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0ZM14 10a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z',
  globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z',
  check:'m5 12 4 4L19 6', circlecheck:'M21 12a9 9 0 1 1-4-7.5M8 11l4 4L21 5',
  refresh:'M20 7a8 8 0 1 0 .5 9M20 3v5h-5', copy:'M9 9h12v12H9ZM15 9V3H3v12h6',
  up:'M7 10v11H3V10ZM7 20h10a2 2 0 0 0 2-1.5l2-7A2 2 0 0 0 19 9h-5l1-5-3-2-5 9',
  down:'M7 14V3H3v11ZM7 4h10a2 2 0 0 1 2 1.5l2 7A2 2 0 0 1 19 15h-5l1 5-3 2-5-9',
  download:'M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6', upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6',
  expand:'M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5', back:'M20 12H4m6-6-6 6 6 6',
  shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6ZM8 11l3 3 5-6', user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-3a8 8 0 0 1 16 0v3',
  chart:'M3 3v18h18M7 16v-5M12 16V7M17 16V4', layers:'m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5',
  clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 6v6l4 2', calendar:'M4 5h16v16H4ZM8 2v6M16 2v6M4 10h16',
  spark:'m12 2 2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7Z', filter:'M3 4h18l-7 8v7l-4 2v-9Z',
  external:'M14 3h7v7M10 14 21 3M10 3H3v18h18v-7', image:'M3 3h18v18H3Zm0 14 6-6 4 4 3-3 5 5M9 7h.01',edit:'m14 4 6 6M4 20l5-1L21 7a2 2 0 0 0-4-4L5 15Z'
};
const $ = selector => document.querySelector(selector);
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.file}"/></svg>`;
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconButton = (name, action, label) => `<button class="icon-button" data-action="${action}" aria-label="${label}" title="${label}">${icon(name)}</button>`;
function hydrateIcons() { document.querySelectorAll('i[data-icon]').forEach(node => { node.innerHTML = icon(node.dataset.icon); }); }
const initialTitles = ['苏州三日慢游计划','长沙亲子路线与美食','杭州周末，想去人少的地方','云南旅行预算怎么安排','上海出发的两天一夜','适合带父母去的江南古镇'];
const histories = initialTitles.map((title,id) => ({id:String(id),title,query:id===0?'下个月想去苏州玩三天，两个人，想逛园林、吃当地小吃，节奏轻松一点。帮我安排一下吧。':title, extra:[]}));
const state = { page:'chat', panel:null, active:'0', knowledgeTab:'files', spaceTab:'all', role:'admin', file:null, revision:'2', searchDone:false, searchQuery:'苏州有哪些适合慢慢逛的园林和老街？', selected:[], uploadTarget:'chat', fileQuery:'', city:'全部城市', category:'全部类别' };
const personalFiles = [
 {id:'plan',name:'苏州三日慢游计划.md',type:'md',kind:'plan',size:'4.2 KB',date:'今天 10:42',session:'苏州三日慢游计划',sessionId:'0',version:'v2 · 当前版本'},
 {id:'guide',name:'苏州旅行参考.pdf',type:'pdf',kind:'attachment',size:'2.4 MB',date:'今天 10:36',session:'苏州三日慢游计划',sessionId:'0'},
 {id:'map',name:'想去的地方.png',type:'img',kind:'attachment',size:'846 KB',date:'今天 10:35',session:'苏州三日慢游计划',sessionId:'0'},
 {id:'changsha',name:'长沙亲子路线.md',type:'md',kind:'plan',size:'3.8 KB',date:'昨天 16:08',session:'长沙亲子路线与美食',sessionId:'1',version:'v1 · 当前版本'},
 {id:'hangzhou',name:'杭州周末行程.md',type:'md',kind:'plan',size:'2.9 KB',date:'09月20日',session:'杭州周末，想去人少的地方',sessionId:'2',version:'v1 · 当前版本'},
 {id:'food',name:'想尝试的长沙小吃.txt',type:'txt',kind:'attachment',size:'1.2 KB',date:'昨天 15:47',session:'长沙亲子路线与美食',sessionId:'1'}
];
const knowledgeFiles = [
 {id:'k1',name:'苏州园林与古城漫步指南.md',type:'md',city:'苏州',category:'景点',size:'128 KB',status:'已入库',date:'09月21日 14:32'},
 {id:'k2',name:'苏州地道美食参考.pdf',type:'pdf',city:'苏州',category:'美食',size:'3.2 MB',status:'已入库',date:'09月21日 14:26'},
 {id:'k3',name:'长沙景点与周边游.md',type:'md',city:'长沙',category:'景点',size:'216 KB',status:'已入库',date:'09月20日 09:41'},
 {id:'k4',name:'杭州西湖步行路线.pdf',type:'pdf',city:'杭州',category:'路线',size:'1.8 MB',status:'已入库',date:'09月19日 16:50'},
 {id:'k5',name:'上海城市漫游指南.docx',type:'docx',city:'上海',category:'景点',size:'2.1 MB',status:'已入库',date:'09月19日 11:18'},
 {id:'k6',name:'江南古镇旅行笔记.pdf',type:'pdf',city:'苏州',category:'路线',size:'4.6 MB',status:'解析中',date:'今天 09:20'}
];
let toastTimer;
function toast(text) { $('#toast').textContent=text; $('#toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').hidden=true,3200); }
function activeChat() { return histories.find(item => item.id===state.active); }
function showPage(page) { state.page=page; state.fileQuery=''; state.file=null; $('#app').classList.remove('mobile-open'); render(); }
function renderHistory() {
 const query=$('#history-search input').value.toLowerCase();
 $('#histories').innerHTML=histories.filter(h=>h.title.toLowerCase().includes(query)).map(h=>`<div class="history-item ${state.active===h.id&&state.page==='chat'?'selected':''}"><button data-history="${h.id}" title="${escapeHtml(h.title)}">${escapeHtml(h.title)}</button><button class="icon-button" data-rename="${h.id}" aria-label="重命名${escapeHtml(h.title)}" title="重命名">${icon('edit')}</button></div>`).join('') || '<div class="empty-result">没有匹配的对话</div>';
}
function composer() {return `<div class="composer-area"><form class="composer" id="chat-form"><div class="attachments">${state.selected.map((f,i)=>`<span class="attachment-chip">${icon('file')}${escapeHtml(f.name)}<button type="button" class="icon-button" data-remove="${i}" aria-label="移除${escapeHtml(f.name)}">${icon('close')}</button></span>`).join('')}</div><textarea id="chat-input" aria-label="输入旅行问题" placeholder="聊聊你的旅行想法，也可以添加攻略、行程单或路线图…" rows="2"></textarea><div class="composer-bottom"><div class="row"><button type="button" class="icon-button" data-action="attach" aria-label="添加附件" title="添加附件">${icon('plus')}</button><span class="composer-mode"><span class="dot"></span>旅行规划</span></div><div class="row"><select class="model-select" aria-label="选择模型"><option>DeepSeek Chat</option><option>通义千问</option><option>智谱 GLM</option></select><button class="send" type="submit" aria-label="发送消息">${icon('arrow')}</button></div></div></form><div class="composer-foot">设计预览 · 回复、文件与用量均为示例，不调用真实模型</div></div>`;}
function planCard() {return `<div class="plan-card"><div class="plan-head"><div class="plan-symbol">${icon('file')}</div><div><h2>苏州三日慢游计划</h2><p><span>3 天 2 晚</span><span>·</span><span>双人出游</span><span>·</span><span>轻松慢游</span></p></div><span class="draft-pill">草稿 v2</span></div><div class="plan-days"><div class="day"><div class="day-number">DAY<b>01</b></div><div><h3>走进园林，漫步姑苏古城</h3><p class="route">拙政园 ${icon('right')} 苏州博物馆 ${icon('right')} 平江路</p></div></div><div class="day"><div class="day-number">DAY<b>02</b></div><div><h3>听一曲评弹，尝一味江南</h3><p class="route">留园 ${icon('right')} 山塘街 ${icon('right')} 评弹茶馆</p></div></div><div class="day"><div class="day-number">DAY<b>03</b></div><div><h3>把最后半天，留给喜欢的街巷</h3><p class="route">双塔市集 ${icon('right')} 十全街 ${icon('right')} 返程</p></div></div></div><div class="plan-bottom"><span>已保存至本对话文件</span><button class="text-button" data-file="plan">打开行程草稿 ${icon('right')}</button></div></div>`;}
function processBlock() {return `<details class="process" open><summary>${icon('atom')}<span>已完成</span><span class="process-count">· 3 次工具调用 · 18 秒</span><span class="chev">${icon('chevron')}</span></summary><div class="process-steps"><details class="tool-detail"><summary><div class="tool-row">${icon('book')}<strong>检索知识库</strong><span>苏州 · 园林与古城漫步</span><b class="ok">${icon('check')}</b></div></summary><p>命中 5 个相关片段，采用 2 份参考资料。示例查询：苏州园林、老街、轻松慢游。</p></details><details class="tool-detail"><summary><div class="tool-row">${icon('file')}<strong>读取资料</strong><span>苏州旅行参考.pdf</span><b class="ok">${icon('check')}</b></div></summary><p>已读取相关章节，整理用户希望游览的区域。仅展示公开的结果摘要。</p></details><details class="tool-detail"><summary><div class="tool-row">${icon('map')}<strong>查询地图</strong><span>核对景点位置与游览顺序</span><b class="ok">${icon('check')}</b></div></summary><p>按同一区域归并停留点，减少往返。本设计稿没有执行真实地图查询。</p></details></div></details>`;}
function chatView() {
 const chat=activeChat(); const isEmpty=!chat?.query;
 $('#page-content').className=`page-content chat-page ${isEmpty?'is-empty':''}`;
 let content;
 if(isEmpty) content=`<div class="welcome"><img src="logo-mark.svg" alt=""><h1>下一站，想去哪里？</h1><p>从一个想法开始，把旅途慢慢安排好。</p><div class="suggestions"><button data-suggest="周末想找个地方放松两天">${icon('calendar')}周末短途</button><button data-suggest="帮我规划一趟轻松的亲子旅行">${icon('user')}亲子出游</button><button data-suggest="想去苏州吃当地小吃，逛逛园林">${icon('pin')}城市慢游</button></div></div>`;
 else content=`<div class="messages"><div class="user-message">${escapeHtml(chat.query)}</div><article class="assistant-message"><div class="assistant-byline"><img src="logo-mark.svg" alt=""><strong>TravelMind</strong><span>旅行助手</span></div>${state.active==='0'?`${processBlock()}<p>可以，给你安排一趟<strong>不赶路的苏州慢旅行</strong>。园林放在上午，下午留给老街和小吃，每天只安排两到三个主要停留点。</p>${planCard()}<p>第一天建议住在古城区附近，往返园林和街巷会更从容。博物馆等场馆的预约与开放情况，出发前再核对。<button class="citation" data-action="sources" aria-label="查看参考来源">1</button><button class="citation" data-action="sources" aria-label="查看附件来源">2</button></p><p>你准备从哪里出发？确定后，我可以继续补上往返交通。</p>`:`<p>这是“${escapeHtml(chat.title)}”的历史对话示例。正式接入后，这里会恢复该会话自己的消息、文件与执行记录。</p>`}<div class="message-actions">${iconButton('copy','copy','复制示例回答')}${iconButton('up','like','觉得有帮助')}${iconButton('down','dislike','反馈问题')}<span>DeepSeek Chat · 示例</span></div></article>${chat.extra.map(item=>`<div class="user-message" style="margin-top:28px">${escapeHtml(item)}</div><article class="assistant-message"><p>已收到你的补充。这是设计稿中的示例回应，正式页面将由当前选择的模型继续规划。</p></article>`).join('')}</div>`;
 $('#page-content').innerHTML=content+composer();
 $('#chat-form').addEventListener('submit',e=>{e.preventDefault();sendMessage();});
 $('#chat-input').value=chat?.draft||'';
 $('.model-select').value=state.provider||'DeepSeek Chat';
 $('#chat-input').addEventListener('input',e=>{if(activeChat())activeChat().draft=e.target.value;});
 $('.model-select').addEventListener('change',e=>state.provider=e.target.value);
 $('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendMessage();}});
}
function statusContent() {return `<div class="inspector-head"><span>对话状态</span><div class="row">${iconButton('refresh','refresh-status','刷新状态')}${iconButton('close','close-panel','关闭侧面板')}</div></div><div class="inspector-body"><div class="status-card"><div class="card-label"><span>最近上下文占用</span>${icon('status')}</div><div class="context-amount"><strong>14.4</strong><span>%</span><small>18.4K / 128K</small></div><div class="meter"><span></span></div><div class="stats-pair"><div><span class="stat-name">当前对话累计</span><span class="stat-value">46.8K</span></div><div><span class="stat-name">缓存命中率</span><span class="stat-value">72.6%</span></div></div></div><div class="status-card"><div class="model-title"><span class="model-dot">D</span>DeepSeek Chat<span>6 次调用</span></div><div class="model-metrics"><div><span class="stat-name">输入 / 输出</span><b>41.2K / 5.6K</b></div><div><span class="stat-name">缓存读取</span><b>29.9K</b></div></div></div><div class="inspector-subtitle">${icon('clock')}最近调用<span>本对话</span></div><div class="call-row">${icon('spark')}<div><strong>生成行程草稿</strong><p>输入 18.4K · 输出 2.1K</p></div><span>已完成</span></div><div class="call-row">${icon('book')}<div><strong>整理检索结果</strong><p>输入 8.6K · 输出 1.2K</p></div><span>已完成</span></div><div class="call-row">${icon('edit')}<div><strong>总结对话标题</strong><p>输入 0.8K · 输出 0.1K</p></div><span>已完成</span></div><div class="inspector-subtitle" style="margin-top:20px">${icon('folder')}本次产物<span>1 个</span></div>${fileCard(personalFiles[0])}<p class="small-note">示例统计，用于预览布局。上下文占用按最近一次聊天调用计算；累计用量按整个会话汇总。</p></div>`;}
function fileCard(f){return `<button class="file-card" data-file="${f.id}"><span class="file-type ${f.type}">${f.type==='img'?'IMG':f.type.toUpperCase()}</span><span><strong>${escapeHtml(f.name)}</strong><small>${f.version||f.size+' · 私人附件'}</small></span>${icon('right')}</button>`;}
function filesContent(){const files=personalFiles.filter(f=>f.sessionId===state.active);return `<div class="inspector-head"><span>对话文件 <small>${files.length}</small></span>${iconButton('close','close-panel','关闭侧面板')}</div><div class="inspector-body"><div class="inspector-subtitle">${icon('file')}行程草稿<span>${files.filter(f=>f.kind==='plan').length}</span></div>${files.filter(f=>f.kind==='plan').map(fileCard).join('')||'<p class="small-note">生成的行程会出现在这里。</p>'}<div class="inspector-subtitle" style="margin-top:18px">${icon('folder')}上传附件<span>${files.filter(f=>f.kind==='attachment').length}</span></div>${files.filter(f=>f.kind==='attachment').map(fileCard).join('')||'<p class="small-note">这段对话还没有附件。</p>'}<p class="small-note">仅显示当前对话的文件。全部私人附件和行程草稿可在“个人空间”查看。</p><button class="text-button" style="margin-top:12px" data-page="space">打开个人空间 ${icon('external')}</button></div>`;}
function previewBody(f){if(f.kind==='plan'){let isSuzhou=f.id==='plan';return `<div class="preview-meta"><span>${icon('file')} 行程草稿</span><span>${isSuzhou?'3 天 · 2 人':'历史行程示例'}</span><span>私人文件</span></div><h1 class="preview-title">${escapeHtml(f.name.replace('.md',''))}</h1><p class="small-note">设计示例 · 正式内容将读取对应版本的已保存快照</p>${isSuzhou?`<div class="version-bar">${icon('layers')}行程版本<select id="revision" aria-label="行程版本"><option value="2" ${state.revision==='2'?'selected':''}>v2 · 当前版本</option><option value="1" ${state.revision==='1'?'selected':''}>v1 · 历史版本</option></select></div>${state.revision==='1'?'<p class="small-note">正在预览历史版本：第二天安排为虎丘，后续版本已调整为留园。</p>':''}<section class="preview-day"><h3>01 / 园林与古城</h3><ol><li>上午：拙政园，留出慢慢游览的时间</li><li>下午：苏州博物馆，提前核对预约</li><li>傍晚：平江路，吃小吃、看水巷</li></ol></section><section class="preview-day"><h3>02 / ${state.revision==='1'?'虎丘与山塘街':'留园与山塘街'}</h3><ol><li>上午：${state.revision==='1'?'虎丘':'留园'}，不急着赶下一站</li><li>下午：山塘街，沿河散步</li><li>晚上：找一家评弹茶馆坐坐</li></ol></section><section class="preview-day"><h3>03 / 街巷里的日常</h3><ol><li>上午：双塔市集，吃一顿当地早餐</li><li>午后：十全街，根据返程时间自由安排</li></ol></section><section class="preview-day"><h3>参考资料</h3><p>苏州园林与古城漫步指南.md<br>苏州旅行参考.pdf（私人附件）</p></section>`:`<section class="preview-day"><h3>行程内容</h3><p>这是“${escapeHtml(f.session)}”的文件示例，用于检查跨会话文件展示和返回原对话的交互。</p></section>`}`}if(f.type==='img')return `<h1 class="preview-title">${escapeHtml(f.name)}</h1><p class="small-note">图片附件预览 · 以下为布局占位，不是原始路线图</p><div class="sample-map" style="margin-top:24px"><div class="route">${icon('pin')}园林 ${icon('right')}古城 ${icon('right')}老街</div><small>接入后显示用户上传的真实图片</small></div>`;return `<div class="preview-meta">${icon('file')} ${f.type.toUpperCase()} · ${f.size} · ${f.city||'私人附件'}</div><h1 class="preview-title">${escapeHtml(f.name)}</h1><section class="preview-day"><h3>正文预览</h3><p>这是文件预览样式示例。接入正式资料后，这里显示文件原文，并保留页码、章节和来源位置。</p><p>旅行资料可记录希望游览的景点、餐馆、住宿和交通安排。对话中的引用可以回到相应的原文片段。</p></section><section class="preview-day"><h3>来源信息</h3><p>${escapeHtml(f.session||'管理员共享知识库')}<br>仅用于设计预览，没有读取实际文件正文。</p></section>`;}
function renderPanel(){const panel=$('#inspector');panel.hidden=state.page!=='chat'||!state.panel;panel.className=`inspector ${state.file?'file-inspector':''}`;if(panel.hidden)return;if(state.file){panel.innerHTML=`<div class="inspector-head"><button class="text-button" data-action="back-files">${icon('back')}文件</button><div class="row">${iconButton('expand','expand-file','扩大预览')}${iconButton('download','download','下载示例文件')}${iconButton('close','close-panel','关闭侧面板')}</div></div><div class="file-preview">${previewBody(state.file)}</div>`;bindRevision();}else panel.innerHTML=state.panel==='status'&&state.active==='0'?statusContent():state.panel==='status'?`<div class="inspector-head">对话状态${iconButton('close','close-panel','关闭侧面板')}</div><div class="empty-state">${icon('status')}<p>暂无调用统计</p><small>发送消息后，这里会显示该对话的真实模型用量。</small></div>`:filesContent();}
function fileTableRows(files,knowledge=false){return files.map(f=>`<tr><td><button class="filename" data-file="${f.id}"><span class="file-type ${f.type}">${f.type==='img'?'IMG':f.type.toUpperCase()}</span><span><strong>${escapeHtml(f.name)}</strong><small>${knowledge?f.size:f.version||f.size}</small></span></button></td>${knowledge?`<td>${f.city}</td><td>${f.category}</td><td><span class="status-label ${f.status==='已入库'?'':'wait'}">${icon(f.status==='已入库'?'circlecheck':'clock')}${f.status}</span></td>`:`<td><button class="text-button" data-history="${f.sessionId}">${escapeHtml(f.session)}</button></td><td>${f.kind==='plan'?'行程草稿':'上传附件'}</td>`}<td>${f.date}</td><td><div class="row"><button class="icon-button" data-file="${f.id}" aria-label="预览${escapeHtml(f.name)}" title="预览文件">${icon('expand')}</button><button class="icon-button" data-download="${f.id}" aria-label="下载${escapeHtml(f.name)}" title="下载示例">${icon('download')}</button></div></td></tr>`).join('');}
function table(files,knowledge=false){return `<div class="table-wrap"><table class="file-table"><thead><tr><th>文件名称</th>${knowledge?'<th>城市</th><th>类别</th><th>状态</th>':'<th>所属对话</th><th>类型</th>'}<th>更新时间</th><th>操作</th></tr></thead><tbody id="file-rows">${fileTableRows(files,knowledge)}</tbody></table><div id="files-empty" class="empty-result" ${files.length?'hidden':''}>没有找到匹配的文件</div></div><div class="table-foot"><span id="file-count">共 ${files.length} 份文件</span><span>1 / 1</span></div>`;}
function filterFiles(){let knowledge=state.page==='knowledge';const data=knowledge?knowledgeFiles:personalFiles;return data.filter(f=>f.name.toLowerCase().includes(state.fileQuery.toLowerCase())&&(knowledge?(state.city==='全部城市'||state.city===f.city)&&(state.category==='全部类别'||state.category===f.category):(state.spaceTab==='all'||f.kind===state.spaceTab)));}
function updateTable(){const files=filterFiles();$('#file-rows').innerHTML=fileTableRows(files,state.page==='knowledge');$('#file-count').textContent=`共 ${files.length} 份文件`;$('#files-empty').hidden=!!files.length;}
function fileSearch(){return `<label class="search-field">${icon('search')}<input id="file-search" aria-label="搜索文件" placeholder="搜索文件名称" value="${escapeHtml(state.fileQuery)}"></label>`;}
function spaceView(){ $('#page-content').className='page-content';const plans=personalFiles.filter(f=>f.kind==='plan').length;$('#page-content').innerHTML=`<div class="page-area"><div class="page-heading"><div><div class="page-eyebrow">${icon('drive')} MY SPACE</div><h1>个人空间</h1><p>让每一次旅行的灵感和计划，都有迹可循。</p></div><span class="badge-subtle">${icon('shield')}仅自己可见</span></div><div class="space-summary"><div class="space-stat"><i>${icon('file')}</i><div><strong>行程草稿</strong><p>在对话中生成的旅行计划</p></div><b>${plans}</b></div><div class="space-stat"><i>${icon('folder')}</i><div><strong>上传附件</strong><p>你的攻略、行程单与路线图</p></div><b>${personalFiles.length-plans}</b></div></div><div class="page-tabs"><button data-space-tab="all" class="${state.spaceTab==='all'?'active':''}">全部文件 <b>${personalFiles.length}</b></button><button data-space-tab="plan" class="${state.spaceTab==='plan'?'active':''}">${icon('file')}行程草稿</button><button data-space-tab="attachment" class="${state.spaceTab==='attachment'?'active':''}">${icon('folder')}上传附件</button></div><div class="toolbar"><div class="toolbar-left">${fileSearch()}</div><span class="badge-subtle">最近更新</span></div>${table(filterFiles())}<p class="demo-banner">文件通过对话上传或生成；点击所属对话，可以继续这段旅程。</p></div>`;bindFileFilter();}
function knowledgeView(){ $('#page-content').className='page-content';$('#page-content').innerHTML=`<div class="page-area"><div class="page-heading"><div><div class="page-eyebrow">${icon('books')} KNOWLEDGE BASE</div><h1>旅行知识库</h1><p>管理共享旅行资料，检查每一次检索的依据。</p></div><span class="badge-subtle">管理员空间</span></div><div class="page-tabs"><button class="${state.knowledgeTab==='files'?'active':''}" data-knowledge-tab="files">${icon('folder')}文件管理</button><button class="${state.knowledgeTab==='search'?'active':''}" data-knowledge-tab="search">${icon('search')}检索测试</button></div>${state.knowledgeTab==='files'?`<div class="toolbar"><div class="toolbar-left"><button class="primary-button" data-action="knowledge-upload">${icon('upload')}上传文件</button>${fileSearch()}</div><div class="toolbar-right"><select id="city-filter" class="filter-select" aria-label="按城市筛选">${['全部城市','苏州','长沙','杭州','上海'].map(c=>`<option ${c===state.city?'selected':''}>${c}</option>`).join('')}</select><select id="category-filter" class="filter-select" aria-label="按类别筛选">${['全部类别','景点','美食','路线'].map(c=>`<option ${c===state.category?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="toolbar"><span class="inspector-subtitle" style="padding:0">全部资料</span><div class="stats-inline"><span>${icon('file')}<b>${knowledgeFiles.length}</b>份文件</span><span>${icon('layers')}<b>286</b>个片段</span><span>示例统计</span></div></div>${table(filterFiles(),true)}<p class="demo-banner">上传、解析和索引状态在此统一查看。设计稿中的选择文件不会上传或入库。</p>`:searchView()}</div>`;if(state.knowledgeTab==='files')bindFileFilter();else bindSearch();}
function searchView(){return `<form id="search-form"><div class="search-box"><textarea id="knowledge-query" aria-label="检索问题" placeholder="输入问题，检索知识库中的原文片段…">${escapeHtml(state.searchQuery)}</textarea><div class="search-box-bottom"><span>检查召回内容与来源</span><button class="primary-button" type="submit">${icon('search')}开始检索</button></div></div><div class="search-filters"><span>${icon('filter')} 检索范围</span><select class="filter-select" id="search-city" aria-label="检索城市"><option>全部城市</option><option>苏州</option><option>长沙</option><option>杭州</option><option>上海</option></select><select class="filter-select" id="search-category" aria-label="检索类别"><option>全部类别</option><option>景点</option><option>美食</option><option>路线</option></select><select class="filter-select" id="search-document" aria-label="检索文件"><option value="">全部文件</option>${knowledgeFiles.map(f=>`<option value="${f.id}">${f.name}</option>`).join('')}</select><select class="filter-select" id="search-limit" aria-label="返回数量"><option value="5">返回 5 条</option><option value="10">返回 10 条</option><option value="1">返回 1 条</option></select></div></form><div id="search-results">${state.searchDone?resultsMarkup():`<div class="empty-state">${icon('book')}<p>从一个问题，找到背后的依据</p><small>试试“苏州有哪些适合慢慢逛的园林和老街？”</small></div>`}</div>`;}
function resultsMarkup(){const count=Math.min(Number($('#search-limit')?.value||5),3);const query=state.searchQuery;const city=$('#search-city')?.value||'全部城市';const category=$('#search-category')?.value||'全部类别';const documentId=$('#search-document')?.value||'';if(!/苏州|园林|老街|平江|慢慢|古城/.test(query)||!['全部城市','苏州'].includes(city)||!['全部类别','景点'].includes(category)||(documentId&&documentId!=='k1'))return `<div class="empty-state">${icon('search')}<p>当前示例范围内没有匹配片段</p><small>本稿仅内置苏州园林的检索示例，真实查询将在接入后执行。</small></div>`;return `<div class="results-heading"><span>检索到 <b>${count}</b> 个相关片段 <span style="font-size:9px">· 示例结果</span></span><button class="text-button" data-action="clear-search">清空</button></div>${[{t:'园林与古城，可以这样串起来',p:'拙政园、苏州博物馆与平江路可作为古城游览的一组参考。安排时为园林留出独立游览时间，午后沿平江路散步，根据个人体力调整停留点。',s:'0.0328',c:'园林 / 古城漫步'},{t:'平江路：沿着水巷慢慢走',p:'以街巷步行为主的路线，可以把吃饭、茶馆和休息穿插在游览之间。对于偏好轻松节奏的旅行者，不必在一天里加入过多区域。',s:'0.0301',c:'老街 / 平江路'},{t:'留园与山塘街的半日安排',p:'将园林游览与老街散步分在上午和下午，保留中间的午餐和休息时间。具体交通和场馆开放情况需在出发前核对。',s:'0.0274',c:'园林 / 留园'}].slice(0,count).map((r,i)=>`<article class="hit"><div class="hit-heading"><b>#${i+1}</b><span>检索排序分 ${r.s}</span><span>原文片段</span></div><h3>${r.t}</h3><p>${r.p}</p><div class="hit-footer"><span>${icon('file')} 苏州园林与古城漫步指南.md</span><span>${r.c}</span><span>片段 ${i+12}</span><button data-file="k1">查看原文 ↗</button></div></article>`).join('')}<p class="demo-banner">排序分用于比较检索结果先后，不代表相似度或答案正确率。以上均为设计示例。</p>`;}
function bindFileFilter(){ $('#file-search').addEventListener('input',e=>{state.fileQuery=e.target.value;updateTable();});$('#city-filter')?.addEventListener('change',e=>{state.city=e.target.value;updateTable();});$('#category-filter')?.addEventListener('change',e=>{state.category=e.target.value;updateTable();});}
function bindSearch(){$('#search-form').addEventListener('submit',e=>{e.preventDefault();state.searchQuery=$('#knowledge-query').value.trim();if(!state.searchQuery){toast('请输入要检索的问题');return;}state.searchDone=true;$('#search-results').innerHTML=resultsMarkup();});}
function bindRevision(root=$('#inspector')){root.querySelector('#revision')?.addEventListener('change',e=>{state.revision=e.target.value;if($('#preview-dialog').open){$('#dialog-content').innerHTML=previewBody(state.file);bindRevision($('#dialog-content'));}else renderPanel();});}
function render(){renderHistory();$('#page-title').textContent=state.page==='space'?'个人空间':state.page==='knowledge'?'知识库':activeChat()?.title||'新对话';$('#page-caption').textContent=state.page==='chat'?'私人对话':state.page==='space'?'私人文件':'共享旅行资料';$('#top-actions').hidden=state.page!=='chat';document.querySelectorAll('.nav-item[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===state.page));document.querySelectorAll('[data-panel]').forEach(n=>n.classList.toggle('active',state.panel===n.dataset.panel));document.querySelectorAll('.admin-only').forEach(n=>n.hidden=state.role!=='admin');$('#role-label').textContent=state.role==='admin'?'管理员':'普通用户';if(state.page==='chat')chatView();else if(state.page==='space')spaceView();else knowledgeView();renderPanel();hydrateIcons();const count=personalFiles.filter(f=>f.sessionId===state.active).length;$('.top-tab b').textContent=count;}
function openFile(id){const f=[...personalFiles,...knowledgeFiles].find(f=>f.id===id);if(!f)return;state.file=f;state.revision='2';if(state.page==='chat'){state.panel='files';renderPanel();document.querySelectorAll('[data-panel]').forEach(n=>n.classList.toggle('active',n.dataset.panel==='files'));}else showDialog(f);}
function showDialog(f){$('#preview-dialog [data-action=download]').hidden=false;$('#dialog-title').textContent=f.name;$('#dialog-content').innerHTML=previewBody(f);bindRevision($('#dialog-content'));if(!$('#preview-dialog').open)$('#preview-dialog').showModal();}
function downloadFile(f=state.file){if(!f)return;const text=f.kind==='plan'?`# ${f.name.replace('.md','')}\n\n> TravelMind 交互设计稿的示例文件，不是真实生成的行程。\n\n${f.id==='plan'?`版本：v${state.revision}\n\n## 第一天\n拙政园 → 苏州博物馆 → 平江路\n\n## 第二天\n${state.revision==='1'?'虎丘':'留园'} → 山塘街 → 评弹茶馆\n\n## 第三天\n双塔市集 → 十全街 → 返程`:'正式接入后，将导出对应的行程快照。'}`:`${f.name}\n\n这是交互设计稿的下载说明，不是原文件。正式接入后将下载你有权限访问的原始附件。`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=f.kind==='plan'?f.name:f.name+'.示例说明.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已下载设计示例文件');}
function newChat(){const id=String(Date.now());histories.unshift({id,title:'新对话',query:'',extra:[]});state.active=id;state.panel=null;state.selected=[];showPage('chat');$('#chat-input').focus();}
function sendMessage(){const text=$('#chat-input').value.trim();if(!text&&!state.selected.length)return;let chat=activeChat();if(!chat){newChat();chat=activeChat();}const actual=text||'请参考我选择的附件';chat.draft='';if(!chat.query){chat.query=actual;chat.title=/苏州/.test(actual)?'苏州旅行规划':/亲子/.test(actual)?'轻松亲子旅行':/周末/.test(actual)?'周末短途旅行':actual.slice(0,18);}else chat.extra.push(actual);for(const f of state.selected){personalFiles.push({id:'local-'+crypto.randomUUID(),name:f.name,type:f.name.split('.').at(-1).toLowerCase(),kind:'attachment',size:(f.size/1024).toFixed(1)+' KB',date:'刚刚 · 示例',session:chat.title,sessionId:chat.id});}state.selected=[];const pos=histories.indexOf(chat);histories.splice(pos,1);histories.unshift(chat);render();const area=$('.messages');if(area)area.scrollTop=area.scrollHeight;toast('示例消息已发送；没有调用真实模型或上传文件');}
document.addEventListener('click',async e=>{
 const button=e.target.closest('button,a');if(!button)return;
 if(button.dataset.page){showPage(button.dataset.page);return;}
 if(button.dataset.history){if($('#preview-dialog').open)$('#preview-dialog').close();state.active=button.dataset.history;state.selected=[];state.file=null;showPage('chat');return;}
 if(button.dataset.panel){state.panel=state.panel===button.dataset.panel?null:button.dataset.panel;state.file=null;renderPanel();document.querySelectorAll('[data-panel]').forEach(n=>n.classList.toggle('active',state.panel===n.dataset.panel));return;}
 if(button.dataset.file){openFile(button.dataset.file);return;}
 if(button.dataset.download){downloadFile([...personalFiles,...knowledgeFiles].find(f=>f.id===button.dataset.download));return;}
 if(button.dataset.knowledgeTab){state.knowledgeTab=button.dataset.knowledgeTab;state.fileQuery='';render();return;}
 if(button.dataset.spaceTab){state.spaceTab=button.dataset.spaceTab;render();return;}
 if(button.dataset.suggest){$('#chat-input').value=button.dataset.suggest;$('#chat-input').focus();return;}
 if(button.dataset.role){state.role=button.dataset.role;$('#account-menu').hidden=true;$('.profile').setAttribute('aria-expanded','false');if(state.role==='user'&&state.page==='knowledge')state.page='chat';render();toast(`已切换为${state.role==='admin'?'管理员':'普通用户'}预览，不影响真实账号`);return;}
 if(button.dataset.remove!==undefined){const value=$('#chat-input').value;state.selected.splice(Number(button.dataset.remove),1);chatView();$('#chat-input').value=value;return;}
 if(button.dataset.rename){state.file=null;$('#preview-dialog [data-action=download]').hidden=true;const h=histories.find(h=>h.id===button.dataset.rename);$('#dialog-title').textContent='重命名对话';$('#dialog-content').innerHTML=`<form id="rename-form" style="padding:20px 0"><label class="search-field"><input aria-label="新的对话标题" value="${escapeHtml(h.title)}" maxlength="40" style="width:100%" required></label><div class="row" style="justify-content:flex-end;margin-top:20px"><button type="button" class="secondary-button" data-action="close-dialog">取消</button><button class="primary-button">保存</button></div></form>`;$('#rename-form').onsubmit=event=>{event.preventDefault();const title=$('#rename-form input').value.trim();if(!title)return;h.title=title;personalFiles.filter(f=>f.sessionId===h.id).forEach(f=>f.session=title);$('#preview-dialog').close();render();};$('#preview-dialog').showModal();return;}
 switch(button.dataset.action){
 case 'new':newChat();break;
 case 'collapse':if(innerWidth<=600)$('#app').classList.remove('mobile-open');else $('#app').classList.toggle('collapsed');break;
 case 'sidebar':if(innerWidth<=600)$('#app').classList.toggle('mobile-open');else $('#app').classList.remove('collapsed');break;
 case 'history-search':$('#history-search').hidden=!$('#history-search').hidden;if(!$('#history-search').hidden)$('#history-search input').focus();break;
 case 'profile':$('#account-menu').hidden=!$('#account-menu').hidden;$('.profile').setAttribute('aria-expanded',String(!$('#account-menu').hidden));break;
 case 'close-panel':state.panel=null;state.file=null;renderPanel();document.querySelectorAll('[data-panel]').forEach(n=>n.classList.remove('active'));break;
 case 'back-files':state.file=null;state.panel='files';renderPanel();break;
 case 'expand-file':showDialog(state.file);break;
 case 'close-dialog':$('#preview-dialog').close();break;
 case 'download':downloadFile();break;
 case 'refresh-status':toast('当前为示例统计，正式接入后刷新真实调用数据');break;
 case 'copy':try{await navigator.clipboard.writeText($('.assistant-message').innerText);toast('示例回答已复制');}catch{toast('浏览器暂不允许复制，可选择正文复制');}break;
 case 'like':case 'dislike':toast('已记录本次设计预览中的反馈');break;
 case 'sources':state.file=null;state.panel='files';renderPanel();break;
 case 'attach':state.uploadTarget='chat';$('#local-files').click();break;
 case 'knowledge-upload':state.uploadTarget='knowledge';$('#local-files').click();break;
 case 'clear-search':state.searchDone=false;$('#search-results').innerHTML='<div class="empty-state">检索结果已清空，可以重新输入问题。</div>';break;
 case 'costs':$('#account-menu').hidden=true;toast(state.role==='admin'?'正式页面将保留现有管理员费用账本入口':'仅管理员可以查看调用费用');break;
 }
});
document.addEventListener('click',e=>{if(!e.target.closest('.profile,#account-menu')){$('#account-menu').hidden=true;$('.profile').setAttribute('aria-expanded','false');}});
$('#history-search input').addEventListener('input',renderHistory);
$('#local-files').addEventListener('change',e=>{const files=[...e.target.files];if(!files.length)return;if(state.uploadTarget==='chat'){const value=$('#chat-input').value;state.selected.push(...files.slice(0,Math.max(0,3-state.selected.length)));chatView();$('#chat-input').value=value;toast('已选择文件（最多 3 份），仅在此设计稿中展示');}else{for(const f of files)knowledgeFiles.unshift({id:'local-k-'+crypto.randomUUID(),name:f.name,type:f.name.split('.').at(-1).toLowerCase(),city:'未分类',category:'未分类',size:(f.size/1024).toFixed(1)+' KB',status:'待上传 · 示例',date:'刚刚'});render();toast('文件名已加入示例列表，没有上传或建立索引');}e.target.value='';});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#app').classList.remove('mobile-open');$('#account-menu').hidden=true;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&!$('#preview-dialog').open){e.preventDefault();newChat();}});
$('.brand').addEventListener('click',e=>{e.preventDefault();showPage('chat');});
render();
